# Generated by Django 6.0.4 on 2026-06-27 13:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Full credential name (e.g. 'Certified Full-Stack Developer — Django & React').", max_length=300, verbose_name='Credential Title')),
                ('issuer', models.CharField(help_text="Issuing organisation (e.g. 'WabiSkills').", max_length=200)),
                ('year', models.CharField(help_text="Four-digit year of issue (e.g. '2024').", max_length=4, validators=[django.core.validators.MaxLengthValidator(4)])),
                ('description', models.TextField(help_text='One or two sentences describing what this credential validates.')),
                ('verify_link', models.URLField(blank=True, help_text="Link to the issuer's credential verification page. Leave blank if not available.", null=True, verbose_name='Verify URL')),
                ('badge', models.ImageField(blank=True, help_text='Optional certification badge image (PNG with transparent background recommended).', null=True, upload_to='certifications/')),
                ('order', models.IntegerField(default=0, help_text='Display order — lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text="Year label as displayed (e.g. '2024 - Present' or 'Now').", max_length=30)),
                ('role', models.CharField(help_text="Short title for this milestone (e.g. 'WabiSkills Certification').", max_length=200, verbose_name='Title / Role')),
                ('company', models.CharField(help_text="Organisation name or context (e.g. 'WabiSkills', 'Self-Directed').", max_length=200, verbose_name='Organisation / Context')),
                ('description', models.TextField(help_text='Two-to-three sentence description of what happened during this period.')),
                ('order', models.IntegerField(default=0, help_text='Display order — lower numbers appear first (top of timeline).')),
            ],
            options={
                'verbose_name': 'Experience / Timeline Entry',
                'verbose_name_plural': 'Experience / Timeline Entries',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nabonsi Niguse', max_length=100)),
                ('title', models.CharField(default='Full-Stack Software Engineer', max_length=200)),
                ('bio_paragraphs', models.TextField(help_text='Newline-separated paragraphs for the About section.')),
                ('avatar', models.ImageField(blank=True, help_text='Upload your profile photo here.', null=True, upload_to='profile/')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Hire')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='One punchy sentence describing what the project does and why.')),
                ('tags', models.CharField(help_text="Comma-separated tech stack tags shown on the card (e.g. 'Django, React, PostgreSQL, Tailwind CSS'). Serialized as a JSON array by the API.", max_length=500)),
                ('bullet_points', models.TextField(help_text='One feature highlight per line. Each line becomes one bullet in the highlights array. Example:\n  Role-based access: instructor, student, and admin dashboards\n  JWT authentication with token refresh flow')),
                ('github_link', models.URLField(blank=True, help_text='Link to the GitHub repository. Leave blank if private.', null=True, verbose_name='GitHub URL')),
                ('live_link', models.URLField(blank=True, help_text='Link to the deployed demo. Leave blank if not available.', null=True, verbose_name='Live Demo URL')),
                ('image', models.ImageField(blank=True, help_text='Optional project screenshot (PNG or JPG, 16:9 recommended).', null=True, upload_to='projects/')),
                ('order', models.IntegerField(default=0, help_text='Display order — lower numbers appear first (leftmost card).')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Database', 'Database'), ('Core & Networking', 'Core & Networking')], help_text='The skill group label shown on the frontend card.', max_length=30, unique=True)),
                ('icon_name', models.CharField(help_text="Lucide icon component name (e.g. 'Code2', 'Globe', 'Database', 'Network'). Must match an exported name from lucide-react.", max_length=60)),
                ('order', models.IntegerField(default=0, help_text='Display order — lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Skill Group',
                'verbose_name_plural': 'Skill Groups',
                'ordering': ['order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Skill label exactly as it should appear on the badge (e.g. 'Django REST Framework').", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order within this group — lower numbers appear first.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillgroup')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
    ]
