# Generated by Django 5.1.4 on 2026-06-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='badge',
            field=models.ImageField(blank=True, help_text='Optional certification badge image (PNG with transparent background recommended).', null=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuer',
            field=models.CharField(help_text="Issuing organisation (e.g. 'WabiSkills').", max_length=200),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(help_text="Full credential name (e.g. 'Certified Full-Stack Developer — Django & React').", max_length=300, verbose_name='Credential Title'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='verify_link',
            field=models.URLField(blank=True, help_text="Link to the issuer's credential verification page. Leave blank if not available.", null=True, verbose_name='Verify URL'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(help_text="Organisation name or context (e.g. 'WabiSkills', 'Self-Directed').", max_length=200, verbose_name='Organisation / Context'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(help_text='Two-to-three sentence description of what happened during this period.'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order — lower numbers appear first (top of timeline).'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(help_text="Short title for this milestone (e.g. 'WabiSkills Certification').", max_length=200, verbose_name='Title / Role'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bullet_points',
            field=models.TextField(help_text='One feature highlight per line. Each line becomes one bullet in the highlights array. Example:\n  Role-based access: instructor, student, and admin dashboards\n  JWT authentication with token refresh flow'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, help_text='Link to the GitHub repository. Leave blank if private.', null=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional project screenshot (PNG or JPG, 16:9 recommended).', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, help_text='Link to the deployed demo. Leave blank if not available.', null=True, verbose_name='Live Demo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order — lower numbers appear first (leftmost card).'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(help_text="Comma-separated tech stack tags shown on the card (e.g. 'Django, React, PostgreSQL, Tailwind CSS'). Serialized as a JSON array by the API.", max_length=500),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text="Skill label exactly as it should appear on the badge (e.g. 'Django REST Framework').", max_length=100),
        ),
    ]
